name: DRACO
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - armadillo=14.0.3=hfda7a17_0
  - arpack=3.9.1=nompi_h77f6705_101
  - binutils_impl_linux-64=2.43=h4bf12b8_1
  - blis=0.9.0=h4ab18f5_2
  - boost=1.85.0=h9cebb41_4
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.2=heb4867d_0
  - ca-certificates=2024.8.30=hbcca054_0
  - cmake=3.30.5=hf9cb763_0
  - dlib-cpp=19.24.6=h697bdda_0
  - gcc=14.2.0=h96c4ede_1
  - gcc_impl_linux-64=14.2.0=h6b349bd_1
  - gxx=14.2.0=h96c4ede_1
  - gxx_impl_linux-64=14.2.0=h2c03514_1
  - icu=75.1=he02047a_0
  - kernel-headers_linux-64=3.10.0=he073ed8_17
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h712a8e2_1
  - libblas=3.9.0=24_linux64_blis
  - libboost=1.85.0=h0ccab89_4
  - libboost-devel=1.85.0=h00ab1b0_4
  - libboost-headers=1.85.0=ha770c72_4
  - libboost-python=1.85.0=py312hf74af30_4
  - libboost-python-devel=1.85.0=py312h9cebb41_4
  - libcblas=3.9.0=24_linux64_blis
  - libcurl=8.10.1=hbbe4b11_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-devel_linux-64=14.2.0=h41c2201_101
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - libhwloc=2.11.1=default_hecaa2ac_1000
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=7_ha36c22a_netlib
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.28=pthreads_h94d23a6_0
  - libpng=1.6.44=hadc24fc_0
  - libsanitizer=14.2.0=h2a3dede_1
  - libsqlite=3.47.0=hadc24fc_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-devel_linux-64=14.2.0=h41c2201_101
  - libstdcxx-ng=14.2.0=h4852527_1
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.49.2=hb9d3cd8_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=he7c6b58_4
  - libzlib=1.3.1=hb9d3cd8_2
  - make=4.4.1=hb9d3cd8_2
  - ncurses=6.5=he02047a_1
  - numpy=1.26.4=py312heda63a1_0
  - openblas=0.3.28=pthreads_hbcdf1e8_0
  - openssl=3.3.2=hb9d3cd8_0
  - pip=24.2=pyh8b19718_1
  - pkg-config=0.29.2=h4bc722e_1009
  - pkgconfig=1.5.5=pyhd8ed1ab_4
  - python=3.12.7=hc5c86c4_0_cpython
  - python_abi=3.12=5_cp312
  - readline=8.2=h8228510_1
  - rhash=1.4.5=hb9d3cd8_0
  - rust=1.81.0=h1a8d7c4_0
  - rust-std-x86_64-unknown-linux-gnu=1.81.0=h2c6d0dc_0
  - setuptools=75.1.0=pyhd8ed1ab_0
  - superlu=5.2.2=h00795ac_0
  - sysroot_linux-64=2.17=h4a8ded7_17
  - tbb=2021.13.0=h84d6215_0
  - tbb-devel=2021.13.0=h94b29a5_0
  - tk=8.6.13=noxft_h4845f30_101
  - tzdata=2024b=hc8b5060_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zstd=1.5.6=ha6fb4c9_0
